name = "browser"
main = "src/index.js"
compatibility_date = "2024-07-01"

[env.production]
name = "browser"

[env.dev]
name = "browser"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



